# Generated by Django 5.0.3 on 2024-04-19 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecine', '0003_orderstatus_usermedecine_shared_reserved_qty_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='user_medicine',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='medecine.usermedecine'),
            preserve_default=False,
        ),
    ]
